file:
    upload-dir: ./uploads
server:
    port: 8080
spring:
    datasource:
        password: 'adhan4323041'
        url: jdbc:mysql://localhost:3306/backendAPI
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 50MB
            max-request-size: 75MB


#server.port=8080
#
### MULTIPART (MultipartProperties)
## Enable multipart uploads
#spring.servlet.multipart.enabled=true
## Threshold after which files are written to disk.
#spring.servlet.multipart.file-size-threshold=2KB
## Max file size.
#spring.servlet.multipart.max-file-size=50MB
## Max Request Size
#spring.servlet.multipart.max-request-size=75MB
#
### File Storage Properties
## All files uploaded through the REST API will be stored in this directory
#file.upload-dir=./uploads
#
#
#
##MYSQL
#spring.datasource.url=jdbc:mysql://localhost:3306/backendAPI
#spring.datasource.username=root
#spring.datasource.password=
#
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
#
#spring.jpa.show-sql=true
#
#spring.jpa.hibernate.ddl-auto=update